const recherche = document.getElementById('recherche')
const presentation = document.getElementById('presentation')
const chapter_zone = document.getElementById('zone_des_chapitres')
const navbar = document.getElementById('navbar')
const pres_king = document.getElementById('present_king')
const zap_bar = document.getElementById('zap_bar')

//Constantes des titres
const btn_king = document.getElementById('king_btn')
//Constantes des chapitres
const ch_one = document.getElementById('ch_one')
const ch_two = document.getElementById('ch_twoo')
const ch_three = document.getElementById('ch_three')
const ch_four = document.getElementById('ch_fourr')
const ch_five = document.getElementById('ch_fivee')
//Constantes des bouttons
const btn1 = document.getElementById('king_ch_one')
const btn2 = document.getElementById('king_ch_two')
const btn3 = document.getElementById('king_ch_three')
const btn4 = document.getElementById('king_ch_four')
const btn5 = document.getElementById('king_ch_five')
const n_0 = document.getElementById('n_0')
const n_1 = document.getElementById('n_1')
const n_2 = document.getElementById('n_2')
const n_3 = document.getElementById('n_3')
const n_4 = document.getElementById('n_4')
const n_5 = document.getElementById('n_5')
const nb_0 = document.getElementById('nb_0')
const nb_2 = document.getElementById('nb_2')
const nb_3 = document.getElementById('nb_3')
const nb_4 = document.getElementById('nb_4')
